version: '3.8'

services:
  app-frontend:
    build:
      context: ./my-app-frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    networks:
      - app-network

  app-backend:
    build:
      context: ./my-app-backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - app-network
    depends_on:
      - app-database

  app-database:
    image: mongo:latest
    volumes:
      - mongodb-data-container:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data-container: